spring:
  application:
    name: OAuth

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

kakao:
  client-id: ${REST_API_KEY}
  token-uri: https://kauth.kakao.com/oauth/token
  redirect-uri: http://localhost:8080/sign-in/kakao
  userinfo-uri: https://kapi.kakao.com/v2/user/me
